version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
      - mongo
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: myapp
      DB_USER: root
      DB_PASS: password
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: myapp
      MONGO_USER: root
      MONGO_PASS: password
      APP_ENV: development
      APP_DEBUG: 'true'
      APP_SECRET: mysecret
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: myemail@gmail.com
      MAIL_PASSWORD: mypassword
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: myemail@gmail.com
      MAIL_FROM_NAME: My App

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    volumes:
      - db_data:/var/lib/mysql

  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: myapp
    volumes:
      - mongo_data:/data/db

volumes:
  db_data:
  mongo_data: